language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# workaround to get a recent pip version that is able to handle the order of
# dependencies
before_install:
  - pip install -U pip
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
# command to run tests
script:
  - nosetests --with-coverage --cover-package=cine
after_success:
  - coveralls
